const SOCIAL={roblox:'https://www.roblox.com/users/4818300014/profile',instagram:'https://www.instagram.com/manvith_1005?igsh=bWppbzBxZWc5emhv',discord:'https://discord.gg/nGqKXKNKsW'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sortNum=(a,b)=>(a.number||0)-(b.number||0);
const gameSlides={};
function icon(type){if(type==='roblox')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5.2 2.8 21.2 7l-4.2 16-16-4.2 4.2-16Zm3.1 5.1-1.6 6.1 6.1 1.6 1.6-6.1-6.1-1.6Z"/></svg>';if(type==='instagram')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7Zm5 3.5A4.5 4.5 0 1 1 7.5 12 4.5 4.5 0 0 1 12 7.5Zm0 2A2.5 2.5 0 1 0 14.5 12 2.5 2.5 0 0 0 12 9.5ZM17.3 6.2a1.1 1.1 0 1 1-1.1 1.1 1.1 0 0 1 1.1-1.1Z"/></svg>';return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19.5 5.2A16.5 16.5 0 0 0 15.4 4l-.5 1a15.1 15.1 0 0 0-5.8 0l-.5-1a16.5 16.5 0 0 0-4.1 1.2C1.9 8.2 1.2 11 1.4 13.8A16.7 16.7 0 0 0 6.5 16l1.2-1.5c-.7-.2-1.3-.6-1.9-1 2.4 1.1 5.2 1.6 8.1 1.6s5.7-.5 8.1-1.6c-.6.4-1.2.8-1.9 1l1.2 1.5a16.7 16.7 0 0 0 5.1-2.2c.3-3.3-.6-6.1-4.9-8.6ZM8.2 12.3c-.8 0-1.5-.7-1.5-1.6s.7-1.6 1.5-1.6 1.5.7 1.5 1.6-.7 1.6-1.5 1.6Zm7.6 0c-.8 0-1.5-.7-1.5-1.6s.7-1.6 1.5-1.6 1.5 1.6 1.5 1.6Z"/></svg>'}
function socialNav(){return `<div class="socials"><a class="social-btn" href="${SOCIAL.roblox}" target="_blank" rel="noopener">${icon('roblox')}<span>Roblox</span></a><a class="social-btn" href="${SOCIAL.instagram}" target="_blank" rel="noopener">${icon('instagram')}<span>Instagram</span></a><a class="social-btn" href="${SOCIAL.discord}" target="_blank" rel="noopener">${icon('discord')}<span>Discord</span></a></div>`}
function nav(active=''){return `<header class="nav"><a class="brand" href="index.html">ZYREXCORE <span>// PROFILE</span></a><div class="nav-right"><nav class="nav-links"><a href="games.html" class="${active==='games'?'active':''}">Games</a><a href="gfx.html" class="${active==='gfx'?'active':''}">GFX</a><a href="models.html" class="${active==='models'?'active':''}">3D Models</a></nav>${socialNav()}</div></header>`}
function bootChrome(active){document.body.insertAdjacentHTML('afterbegin','<div class="cursor-light" id="cursorLight"></div>'+nav(active));document.body.insertAdjacentHTML('beforeend','<div class="lightbox" id="lightbox"><button class="close" onclick="closeLightbox()">Close ✕</button><img id="lightboxImg" alt="Preview"></div>');const c=document.getElementById('cursorLight');window.addEventListener('pointermove',e=>{c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'})}
async function manifest(){const r=await fetch(`portfolio-manifest.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('Portfolio manifest could not be loaded.');return r.json()}
function imgPath(file){return `assets/${encodeURIComponent(file)}`}
function card(item,label,click=false){return `<article class="card reveal" ${click?`onclick="openLightbox('${esc(imgPath(item.file))}')" style="cursor:zoom-in"`:''}><div class="media"><img src="${esc(imgPath(item.file))}" alt="${esc(item.title)}" loading="lazy" decoding="async"></div><div class="card-body"><div class="kicker">${esc(label)}</div><h3>${esc(item.title)}</h3></div></article>`}
function empty(text){return `<div class="empty">No ${text} yet. Add numbered files to <b>assets/</b>.</div>`}
async function renderAssets(type,containerId,label){const box=document.getElementById(containerId);try{const all=await manifest();const items=all.filter(x=>x.type===type).sort(sortNum);box.innerHTML=items.length?items.map(x=>card(x,label,type!=='game')).join(''):empty(label.toLowerCase())}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function gameCard(g){const imgs=Array.isArray(g.thumbnails)?g.thumbnails.filter(Boolean).slice(0,10):[];const id=`game-${g.number}`;gameSlides[g.number]={imgs,index:0};const hasLink=g.url&&g.url!=='#';const media=imgs.length?`<div class="game-carousel" id="${id}"><img class="game-slide" id="${id}-img" src="${esc(imgs[0])}" alt="${esc(g.title)}" loading="lazy" decoding="async">${imgs.length>1?`<button class="slide-btn prev" onclick="event.stopPropagation();changeGameSlide(${g.number},-1)" aria-label="Previous image">‹</button><button class="slide-btn next" onclick="event.stopPropagation();changeGameSlide(${g.number},1)" aria-label="Next image">›</button><div class="slide-count" id="${id}-count">1 / ${imgs.length}</div>`:''}</div>`:`<div class="game-placeholder"><span>ROBLOX</span><small>${g.url==='#'?'LINK PENDING':'THUMBNAILS UNAVAILABLE'}</small></div>`;return `<article class="card reveal"><div class="media game-media">${media}</div><div class="card-body"><div class="kicker">ROBLOX GAME ${String(g.number).padStart(2,'0')}</div><h3 class="game-name">${esc(g.title)}</h3><p class="game-description">${esc(g.description||'No description available from Roblox.')}</p><div class="card-actions">${hasLink?`<a class="btn primary" href="${esc(g.url)}" target="_blank" rel="noopener">▶ Play on Roblox</a>`:`<span class="btn" style="opacity:.5;cursor:not-allowed">Link Pending</span>`}</div></div></article>`}
function changeGameSlide(number,dir){const s=gameSlides[number];if(!s||s.imgs.length<2)return;s.index=(s.index+dir+s.imgs.length)%s.imgs.length;const img=document.getElementById(`game-${number}-img`);const count=document.getElementById(`game-${number}-count`);if(img)img.src=s.imgs[s.index];if(count)count.textContent=`${s.index+1} / ${s.imgs.length}`}
async function renderGames(containerId,limit=Infinity){const box=document.getElementById(containerId);try{const all=await manifest();const games=all.filter(x=>x.type==='game').sort(sortNum).slice(0,limit);box.innerHTML=games.length?games.map(gameCard).join(''):empty('games')}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function openLightbox(src){const l=document.getElementById('lightbox');document.getElementById('lightboxImg').src=src;l.classList.add('open')}function closeLightbox(){document.getElementById('lightbox').classList.remove('open')}document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});
