const GAME_CONFIG=[{number:1,placeId:'138590507775487',name:'High Cortisol Obby',url:'https://www.roblox.com/games/138590507775487/High-Cortisol-Obby',fallbackDescription:''},{number:2,placeId:'113850844866673',name:'OBBY BUT YOU ARE WITH CLONES',url:'https://www.roblox.com/games/113850844866673/OBBY-BUT-YOU-ARE-WITH-CLONES',fallbackDescription:''},{number:3,placeId:'',name:'Game 3 — Pending',url:'#',fallbackDescription:'Roblox link coming soon.'}];
const SOCIAL={roblox:'https://www.roblox.com/users/4818300014/profile',instagram:'https://www.instagram.com/manvith_1005?igsh=bWppbzBxZWc5emhv',discord:'https://discord.gg/nGqKXKNKsW'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sortNum=(a,b)=>(a.number||0)-(b.number||0);
function icon(type){if(type==='roblox')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5.2 2.8 21.2 7l-4.2 16-16-4.2 4.2-16Zm3.1 5.1-1.6 6.1 6.1 1.6 1.6-6.1-6.1-1.6Z"/></svg>';if(type==='instagram')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7Zm5 3.5A4.5 4.5 0 1 1 7.5 12 4.5 4.5 0 0 1 12 7.5Zm0 2A2.5 2.5 0 1 0 14.5 12 2.5 2.5 0 0 0 12 9.5ZM17.3 6.2a1.1 1.1 0 1 1-1.1 1.1 1.1 1.1 0 0 1 1.1-1.1Z"/></svg>';return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19.5 5.2A16.5 16.5 0 0 0 15.4 4l-.5 1a15.1 15.1 0 0 0-5.8 0l-.5-1a16.5 16.5 0 0 0-4.1 1.2C1.9 8.2 1.2 11 1.4 13.8A16.7 16.7 0 0 0 6.5 16l1.2-1.5c-.7-.2-1.3-.6-1.9-1 2.4 1.1 5.2 1.6 8.1 1.6s5.7-.5 8.1-1.6c-.6.4-1.2.8-1.9 1l1.2 1.5a16.7 16.7 0 0 0 5.1-2.2c.3-3.3-.6-6.1-4.9-8.6ZM8.2 12.3c-.8 0-1.5-.7-1.5-1.6s.7-1.6 1.5-1.6 1.5.7 1.5 1.6-.7 1.6-1.5 1.6Zm7.6 0c-.8 0-1.5-.7-1.5-1.6s.7-1.6 1.5-1.6 1.5.7 1.5 1.6-.7 1.6-1.5 1.6Z"/></svg>'}
function socialNav(){return `<div class="socials"><a class="social-btn" href="${SOCIAL.roblox}" target="_blank" rel="noopener">${icon('roblox')}<span>Roblox</span></a><a class="social-btn" href="${SOCIAL.instagram}" target="_blank" rel="noopener">${icon('instagram')}<span>Instagram</span></a><a class="social-btn" href="${SOCIAL.discord}" target="_blank" rel="noopener">${icon('discord')}<span>Discord</span></a></div>`}
function nav(active=''){return `<header class="nav"><a class="brand" href="index.html">ZYREXCORE <span>// PROFILE</span></a><div class="nav-right"><nav class="nav-links"><a href="games.html" class="${active==='games'?'active':''}">Games</a><a href="gfx.html" class="${active==='gfx'?'active':''}">GFX</a><a href="models.html" class="${active==='models'?'active':''}">3D Models</a></nav>${socialNav()}</div></header>`}
function bootChrome(active){document.body.insertAdjacentHTML('afterbegin','<div class="cursor-light" id="cursorLight"></div>'+nav(active));document.body.insertAdjacentHTML('beforeend','<div class="lightbox" id="lightbox"><button class="close" onclick="closeLightbox()">Close ✕</button><img id="lightboxImg" alt="Preview"></div>');const c=document.getElementById('cursorLight');window.addEventListener('pointermove',e=>{c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'});}
async function manifest(){const r=await fetch(`portfolio-manifest.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('Portfolio manifest could not be loaded.');return r.json()}
function imgPath(file){return `assets/${encodeURIComponent(file)}`}
function card(item,label,click=false){return `<article class="card reveal" ${click?`onclick="openLightbox('${esc(imgPath(item.file))}')" style="cursor:zoom-in"`:''}><div class="media"><img src="${esc(imgPath(item.file))}" alt="${esc(item.title)}" loading="lazy" decoding="async"></div><div class="card-body"><div class="kicker">${esc(label)}</div><h3>${esc(item.title)}</h3></div></article>`}
function empty(text){return `<div class="empty">No ${text} yet. Add numbered files to <b>assets/</b>.</div>`}
async function renderAssets(type,containerId,label){const box=document.getElementById(containerId);try{const all=await manifest();const items=all.filter(x=>x.type===type).sort(sortNum);box.innerHTML=items.length?items.map(x=>card(x,label,type!=='game')).join(''):empty(label.toLowerCase());}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function robloxMeta(game){if(!game.placeId)return game;try{const u=await fetch(`https://apis.roblox.com/universes/v1/places/${game.placeId}/universe`);if(!u.ok)throw Error();const uj=await u.json();const r=await fetch(`https://games.roblox.com/v1/games?universeIds=${uj.universeId}`);if(!r.ok)throw Error();const j=await r.json();const d=j.data&&j.data[0];if(d){return {...game,name:d.name||game.name,description:d.description||game.fallbackDescription||'',universeId:uj.universeId}}}catch(e){}return game}
function gameCard(g){const hasLink=g.url&&g.url!=='#';return `<article class="card reveal"><div class="media"><img src="${esc(imgPath('game'+g.number+'.png'))}" alt="${esc(g.name)}" loading="lazy" onerror="this.parentElement.parentElement.remove()"></div><div class="card-body"><div class="kicker">ROBLOX GAME ${String(g.number).padStart(2,'0')}</div><h3 class="game-name">${esc(g.name)}</h3><p class="game-description">${esc(g.description||'Loading description from Roblox…')}</p><div class="card-actions">${hasLink?`<a class="btn primary" href="${esc(g.url)}" target="_blank" rel="noopener">▶ Play on Roblox</a>`:`<span class="btn" style="opacity:.5;cursor:not-allowed">Link Pending</span>`}</div></div></article>`}
async function renderGames(containerId,limit=Infinity){const box=document.getElementById(containerId);try{const all=await manifest();const manifestGames=all.filter(x=>x.type==='game').sort(sortNum);const games=GAME_CONFIG.map(cfg=>{const m=manifestGames.find(x=>x.number===cfg.number);return {...cfg,...m}}).sort(sortNum).slice(0,limit);box.innerHTML=games.length?games.map(gameCard).join(''):empty('games');games.forEach(async g=>{const d=await robloxMeta(g);const cardEl=[...box.querySelectorAll('.card')].find(el=>el.querySelector('.game-name')?.textContent===g.name||el.querySelector('.kicker')?.textContent.includes(String(g.number).padStart(2,'0')));if(cardEl){cardEl.querySelector('.game-name').textContent=d.name;cardEl.querySelector('.game-description').textContent=d.description||'No description available from Roblox.';}})}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function openLightbox(src){const l=document.getElementById('lightbox');document.getElementById('lightboxImg').src=src;l.classList.add('open')}function closeLightbox(){document.getElementById('lightbox').classList.remove('open')}document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});
